version: '3.8'
name: 'booking-blitz'
services:
  blitz_api:
    container_name: blitz_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:2345'
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - .env
  blitz_client:
    container_name: blitz_client
    build:
      context: ./booking-blitz
      dockerfile: Dockerfile
    ports:
      - '${CLIENT_PORT}:3000'
    volumes:
      - ./booking-blitz:/app
      - /app/node_modules
    env_file:
      - .env